-- 사용자 기본 정보와 소셜 로그인 식별자 저장 테이블 생성
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255),
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(2048),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    provider VARCHAR(20) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

-- 동일 OAuth 제공자의 동일 사용자 중복 가입 방지 인덱스 생성
CREATE UNIQUE INDEX users_provider_provider_id_uk ON users (provider, provider_id);
CREATE UNIQUE INDEX users_email_uk ON users (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX users_nickname_uk ON users (nickname);

-- 사진 촬영 장소와 PostGIS 위치 정보 저장 테이블 생성
CREATE TABLE spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    kakao_place_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    location GEOMETRY(POINT, 4326) NOT NULL,
    address VARCHAR(500),
    description TEXT,
    thumbnail_url VARCHAR(2048),
    view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

-- 지도·피드 조회 성능 인덱스는 실제 측정 후 별도 버전 마이그레이션으로 추가

-- 사진 게시물과 EXIF 촬영 정보 저장 테이블 생성
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    spot_id BIGINT NOT NULL REFERENCES spots (id),
    image_url VARCHAR(2048) NOT NULL,
    description TEXT,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    iso INTEGER,
    aperture DOUBLE PRECISION,
    shutter_speed VARCHAR(50),
    focal_length DOUBLE PRECISION,
    camera_model VARCHAR(255),
    lens_model VARCHAR(255),
    shot_at TIMESTAMPTZ,
    exif_latitude DOUBLE PRECISION,
    exif_longitude DOUBLE PRECISION,
    user_latitude DOUBLE PRECISION,
    user_longitude DOUBLE PRECISION,
    view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
    comment_count INTEGER NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
